### ISSUE TITLE
opencv v1.0.0 refuses to compile with nan v1.5.1

### ISSUE THREAD

**Issue by aujang** [peterbraden/node-opencv#213]
nan recently updated from v1.43 --> 1.5.1, and this causes the following build issue:

<i>../src/Matrix.cc:1266:11: warning: address of local variable ‘ret’ returned [-Wreturn-local-addr]
  cv::Rect ret;
           ^
In file included from ../node_modules/nan/nan.h:63:0,
                 from ../src/OpenCV.h:12,
                 from ../src/Contours.h:1,
                 from ../src/Matrix.cc:1:
../node_modules/nan/nan_new.h: In instantiation of ‘typename NanIntern::Factory<T>::return_t NanNew(A0) [with T = v8::Integer; A0 = long unsigned int; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Integer>]’:
../src/Matrix.cc:453:81:   required from here
../node_modules/nan/nan_new.h:184:41: error: call of overloaded ‘New(long unsigned int&)’ is ambiguous
   return NanIntern::Factory<T>::New(arg0);
                                         ^
../node_modules/nan/nan_new.h:184:41: note: candidates are:
In file included from ../node_modules/nan/nan.h:63:0,
                 from ../src/OpenCV.h:12,
                 from ../src/Contours.h:1,
                 from ../src/Matrix.cc:1:
../node_modules/nan/nan_new.h:86:26: note: static NanIntern::IntegerFactory<T>::return_t NanIntern::IntegerFactory<T>::New(int32_t) [with T = v8::Integer; NanIntern::IntegerFactory<T>::return_t = v8::Local<v8::Integer>; int32_t = int]
   static inline return_t New(int32_t value);
                          ^
../node_modules/nan/nan_new.h:87:26: note: static NanIntern::IntegerFactory<T>::return_t NanIntern::IntegerFactory<T>::New(uint32_t) [with T = v8::Integer; NanIntern::IntegerFactory<T>::return_t = v8::Local<v8::Integer>; uint32_t = unsigned int]
   static inline return_t New(uint32_t value);
                          ^
In file included from ../node_modules/nan/nan.h:63:0,
                 from ../src/OpenCV.h:12,
                 from ../src/Contours.h:1,
                 from ../src/Matrix.cc:1:
../node_modules/nan/nan_new.h: In function ‘typename NanIntern::Factory<T>::return_t NanNew(A0) [with T = v8::Integer; A0 = long unsigned int; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Integer>]’:
../node_modules/nan/nan_new.h:185:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/opencv/src/Matrix.o] Error 1</i>

This can be fixed by forcing nan version 1.4.3 in the project's package.json, but I thought I should bring it to your attention.

**Comment by bobmoff** [comment]
Thanks, your "fix" worked for me!

**Comment by esconone** [comment]
Thanks, it works for me.

**Comment by chovy** [comment]
how do i implement this fix?

**Comment by bobmoff** [comment]
Fork the repo, modify the nan depency to exactly 1.4.3 and use that new repo as a depency in your package.js

This is the fork i did: https://github.com/IMGNRY/node-opencv and use, which works.

**Comment by peterbraden** [comment]
I'm gonna use your fix until I can test with recent versions of nan.

**Comment by aujang** [comment]
Glad I could help. :)

**Comment by peterbraden** [comment]
Closed by #218
